apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: support-chat-dev
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/YOUR_USERNAME/support-chat-platform.git

    targetRevision: dev

    path: k8s/dev

  destination:
    server: https://kubernetes.default.svc

    namespace: support-chat-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true