apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: support-chat-stage
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/taziim/support-chat-platform.git
    targetRevision: stage
    path: k8s/stage

  destination:
    server: https://kubernetes.default.svc
    namespace: support-chat-stage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
