apiVersion: v1
kind: Service

metadata:
  name: chat-frontend
  namespace: support-chat-stage

spec:
  selector:
    app: chat-frontend

  ports:
    - port: 80
      targetPort: 80

  type: ClusterIP